export const ALL_PERMISSIONS = {
    COMPANIES: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/companies', module: "COMPANIES" },
        CREATE: { method: "POST", apiPath: '/api/v1/companies', module: "COMPANIES" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/companies', module: "COMPANIES" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/companies/{id}', module: "COMPANIES" },
        GET_BY_ID: { method: "GET", apiPath: '/api/v1/companies/{id}', module: "COMPANIES" },
        GET_TOP_COMPANIES_TO_CHART: { method: "GET", apiPath: '/api/v1/companies/topcompaniesbyjobs', module: "COMPANIES" },
    },
    JOBS: {
        GET_BY_ID: { method: "GET", apiPath: '/api/v1/jobs/{id}', module: "JOBS" },
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/jobs', module: "JOBS" },
        GET_PAGINATE_ADMIN: { method: "GET", apiPath: '/api/v1/jobs/jobsadmin', module: "JOBS" },
        GET_PAGINATE_BY_COMPANY: { method: "GET", apiPath: '/api/v1/jobs/jobsbycompany', module: "JOBS" },
        GET_JOB_PER_MONTH_TO_CHART: { method: "GET", apiPath: '/api/v1/jobs/jobpermonth', module: "JOBS" },
        GET_JOB_PER_MONTH_FOR_HR_TO_CHART: { method: "GET", apiPath: '/api/v1/jobs/jobpermonthforhr', module: "JOBS" },
        CREATE: { method: "POST", apiPath: '/api/v1/jobs', module: "JOBS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/jobs', module: "JOBS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/jobs/{id}', module: "JOBS" },

    },
    RESUMES: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/resumes', module: "RESUMES" },
        GET_BY_ID: { method: "GET", apiPath: '/api/v1/resumes/{id}', module: "RESUMES" },
        GET_BY_USER: { method: "GET", apiPath: '/api/v1/resumes/by-user', module: "RESUMES" },
        GET_BY_JOB: { method: "GET", apiPath: '/api/v1/resumes/by-job/{id}', module: "RESUMES" },
        CREATE: { method: "POST", apiPath: '/api/v1/resumes', module: "RESUMES" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/resumes', module: "RESUMES" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/resumes/{id}', module: "RESUMES" },
    },
    BLOGS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/blogs', module: "BLOGS" },
        GET_BY_ID: { method: "GET", apiPath: '/api/v1/blogs/{id}', module: "BLOGS" },
        CREATE: { method: "POST", apiPath: '/api/v1/blogs', module: "BLOGS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/blogs', module: "BLOGS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/blogs/{id}', module: "BLOGS" },
    }, 
    SKILLS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/skills', module: "SKILLS" },
        GET_BY_ID: { method: "GET", apiPath: '/api/v1/skills/{id}', module: "SKILLS" },
        CREATE: { method: "POST", apiPath: '/api/v1/skills', module: "SKILLS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/skills', module: "SKILLS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/skills/{id}', module: "SKILLS" },
    },
    ROLES: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/roles', module: "ROLES" },
        GET_BY_ID: { method: "GET", apiPath: '/api/v1/roles/{id}', module: "ROLES" },
        CREATE: { method: "POST", apiPath: '/api/v1/roles', module: "ROLES" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/roles', module: "ROLES" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/roles/{id}', module: "ROLES" },
    },
    PERMISSIONS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/permissions', module: "PERMISSIONS" },
        GET_BY_ID: { method: "GET", apiPath: '/api/v1/permissions/{id}', module: "PERMISSIONS" },
        CREATE: { method: "POST", apiPath: '/api/v1/permissions', module: "PERMISSIONS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/permissions', module: "PERMISSIONS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/permissions/{id}', module: "PERMISSIONS" },
    },
    USERS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/users', module: "USERS" },
        CREATE: { method: "POST", apiPath: '/api/v1/users', module: "USERS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/users', module: "USERS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/users/{id}', module: "USERS" },
        GET_BY_ID: { method: "GET", apiPath: '/api/v1/users/{id}', module: "USERS" },
        UPDATE_PASSWORD: { method: "PUT", apiPath: '/api/v1/users/changepassword', module: "USERS" },    
    },
    SUBSCRIBERS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/subscribers', module: "SUBSCRIBERS" },
        GET_BY_ID: { method: "GET", apiPath: '/api/v1/subscribers/{id}', module: "SUBSCRIBERS" },
        GET_BY_USER: { method: "GET", apiPath: '/api/v1/subscribers/by-user', module: "SUBSCRIBERS" },
        CREATE: { method: "POST", apiPath: '/api/v1/subscribers', module: "SUBSCRIBERS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/subscribers', module: "SUBSCRIBERS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/subscribers/{id}', module: "SUBSCRIBERS" },
    },
    COMMENTS: {
        GET_PAGINATE_BY_BLOG: { method: "GET", apiPath: '/api/v1/comments/blog/{blogId}', module: "COMMENTS" },
        CREATE: { method: "POST", apiPath: '/api/v1/comments', module: "COMMENTS" },
        UPDATE_LIKE: { method: "PUT", apiPath: '/api/v1/comments/like/{commentId}', module: "COMMENTS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/comments/{id}', module: "COMMENTS" },
    },
    TALENTCANDIDATE: {
        GET_PAGINATE_FOR_JOB: { method: "GET", apiPath: '/api/v1/talentcandidate/{id}', module: "TALENTCANDIDATE" },
        CREATE_FOR_JOB: { method: "POST", apiPath: '/api/v1/talentcandidate/{id}', module: "TALENTCANDIDATE" },
        GET_PAGINATE_FOR_COMPANY: { method: "GET", apiPath: '/api/v1/talentcandidate', module: "TALENTCANDIDATE" },
        CREATE_FOR_COMPANY: { method: "POST", apiPath: '/api/v1/talentcandidate', module: "TALENTCANDIDATE" },
    },
    JOBSRECOMMENDATION: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/jobrecommendation', module: "JOBSRECOMMENDATION" },
        CREATE: { method: "POST", apiPath: '/api/v1/jobrecommendation', module: "JOBSRECOMMENDATION" },
    },
    PAYMENTHISTORY: {
        GET_PAGINATE_PAYMENTHISTORY: { method: "GET", apiPath: '/api/v1/payment-history', module: "PAYMENTHISTORY" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/payment-history/{id}', module: "PAYMENTHISTORY" },
        GET_PAYMENTHISTORY_BY_ID: { method: "GET", apiPath: '/api/v1/payment-history/{id}', module: "PAYMENTHISTORY" }
    },
    REPORTS: {
        GET_JOBS: { method: "GET", apiPath: '/api/v1/reports/jobs', module: "REPORTS" },
        GET_JOBS_BY_COMPANY: { method: "GET", apiPath: '/api/v1/reports/jobsbycompany', module: "REPORTS" },
        GET_COMPANIES: { method: "GET", apiPath: '/api/v1/reports/companies', module: "REPORTS" },
        GET_RESUMES: { method: "GET", apiPath: '/api/v1/reports/resumes', module: "REPORTS" },
        GET_RESUMES_BY_COMPANY: { method: "GET", apiPath: '/api/v1/reports/resumesbycompany', module: "REPORTS" },
        GET_USERS: { method: "GET", apiPath: '/api/v1/reports/users', module: "REPORTS" },
    },
    PAYMENTS: {
        GET_CREATE_REDIRECT: { method: "GET", apiPath: '/api/v1/payments/create', module: "PAYMENTS" },
        GET_RETURN_REDIRECT: { method: "GET", apiPath: '/api/v1/payments/return', module: "PAYMENTS" },
    },
}

export const ALL_MODULES = {
    COMPANIES: 'COMPANIES',
    FILES: 'FILES',
    JOBS: 'JOBS',
    BLOGS:'BLOGS',
    RESUMES: 'RESUMES',
    ROLES: 'ROLES',
    PERMISSIONS: 'PERMISSIONS',
    USERS: 'USERS',
    SUBSCRIBERS: 'SUBSCRIBERS',
    COMMENTS:'COMMENTS',
    TALENTCANDIDATE:'TALENTCANDIDATE',
    JOBSRECOMMENDATION:'JOBSRECOMMENDATION',
    PAYMENTHISTORY:'PAYMENTHISTORY',
    REPORTS:'REPORTS',
    PAYMENTS:'PAYMENTS'
}
